"""
Alps2Alps location codes, frozen -- generated by
scripts/build_alps2alps_locations.py (see its docstring for why
frozen and how the deep link is built from these). Codes are the
provider's own stable place ids; regenerate if resorts change or
a link starts 404ing.
"""

#: resort name -> codes for the booking deep link.
ALPS2ALPS_LOCATIONS = {
    "Alpe d'Huez": {'airport_code': 'airport-4', 'airport_name': 'Lyon St Exupery Airport', 'resort_code': 'resort-21', 'resort_name': "Alpe d'Huez"},
    'Avoriaz': {'airport_code': 'airport-1', 'airport_name': 'Geneva Airport', 'resort_code': 'resort-3', 'resort_name': 'Avoriaz 1800 Portes du Soleil'},
    'Bansko': {'airport_code': 'airport-44', 'airport_name': 'Sofia airport', 'resort_code': 'resort-632', 'resort_name': 'Bansko'},
    'Bardonecchia': {'airport_code': 'airport-25', 'airport_name': 'Turin Caselle Airport', 'resort_code': 'resort-143', 'resort_name': 'Bardonecchia'},
    'Cervinia (Breuil-Cervinia)': {'airport_code': 'airport-24', 'airport_name': 'Milano Malpensa Airport', 'resort_code': 'resort-247', 'resort_name': 'Breuil-Cervinia'},
    'Chamonix': {'airport_code': 'airport-1', 'airport_name': 'Geneva Airport', 'resort_code': 'resort-11', 'resort_name': 'Chamonix'},
    "Cortina d'Ampezzo": {'airport_code': 'airport-39', 'airport_name': 'Venice Marco Polo airport', 'resort_code': 'resort-243', 'resort_name': "Cortina d'Ampezzo"},
    'Courchevel': {'airport_code': 'airport-1', 'airport_name': 'Geneva Airport', 'resort_code': 'resort-72', 'resort_name': 'Courchevel 1300 3 Valleys'},
    'Grand Massif (Flaine)': {'airport_code': 'airport-1', 'airport_name': 'Geneva Airport', 'resort_code': 'resort-15', 'resort_name': 'Flaine Grand Massif Haute-Savoie'},
    'Grandvalira (Andorra)': {'airport_code': 'airport-79', 'airport_name': 'Barcelona-El Prat Airport ', 'resort_code': 'resort-754', 'resort_name': 'Andorra la Vella'},
    'Ischgl': {'airport_code': 'airport-19', 'airport_name': 'Innsbruck Airport', 'resort_code': 'resort-168', 'resort_name': 'Ischgl'},
    'Kitzbühel': {'airport_code': 'airport-19', 'airport_name': 'Innsbruck Airport', 'resort_code': 'resort-169', 'resort_name': 'Kitzbuhel'},
    'Les Arcs': {'airport_code': 'airport-1', 'airport_name': 'Geneva Airport', 'resort_code': 'resort-66', 'resort_name': 'Les Arcs 1550,1800, Paradiski'},
    'Les Deux Alpes': {'airport_code': 'airport-4', 'airport_name': 'Lyon St Exupery Airport', 'resort_code': 'resort-27', 'resort_name': 'Les Deux Alpes'},
    'Les Menuires': {'airport_code': 'airport-1', 'airport_name': 'Geneva Airport', 'resort_code': 'resort-77', 'resort_name': 'Les Menuires 3 Valleys'},
    'Livigno': {'airport_code': 'airport-24', 'airport_name': 'Milano Malpensa Airport', 'resort_code': 'resort-240', 'resort_name': 'Livigno – Carosello/Mottolino'},
    'Mayrhofen': {'airport_code': 'airport-19', 'airport_name': 'Innsbruck Airport', 'resort_code': 'resort-165', 'resort_name': 'Mayrhofen'},
    'Méribel': {'airport_code': 'airport-1', 'airport_name': 'Geneva Airport', 'resort_code': 'resort-78', 'resort_name': 'Meribel'},
    'Pamporovo': {'airport_code': 'airport-44', 'airport_name': 'Sofia airport', 'resort_code': 'resort-634', 'resort_name': 'Pamporovo'},
    'Passo Tonale': {'airport_code': 'airport-38', 'airport_name': 'Bergamo airport (Milan Orio)', 'resort_code': 'resort-334', 'resort_name': 'Passo del Tonale'},
    'Saalbach-Hinterglemm': {'airport_code': 'airport-20', 'airport_name': 'Salzburg Airport', 'resort_code': 'resort-172', 'resort_name': 'Saalbach-Hinterglemm'},
    'Serre Chevalier': {'airport_code': 'airport-25', 'airport_name': 'Turin Caselle Airport', 'resort_code': 'resort-28', 'resort_name': 'Serre Chevalier'},
    'St. Anton am Arlberg': {'airport_code': 'airport-19', 'airport_name': 'Innsbruck Airport', 'resort_code': 'resort-166', 'resort_name': 'Lech am Arlberg'},
    'Sölden': {'airport_code': 'airport-19', 'airport_name': 'Innsbruck Airport', 'resort_code': 'resort-175', 'resort_name': 'Sölden/ Soelden'},
    'Val Gardena (Selva)': {'airport_code': 'airport-19', 'airport_name': 'Innsbruck Airport', 'resort_code': 'resort-343', 'resort_name': 'Selva di Cadore'},
    'Val Thorens': {'airport_code': 'airport-1', 'airport_name': 'Geneva Airport', 'resort_code': 'resort-80', 'resort_name': 'Val Thorens 3 Valleys'},
    "Val d'Isère / Tignes": {'airport_code': 'airport-1', 'airport_name': 'Geneva Airport', 'resort_code': 'resort-58', 'resort_name': "Tignes L'Espace Killy Savoie"},
    'Verbier': {'airport_code': 'airport-1', 'airport_name': 'Geneva Airport', 'resort_code': 'resort-224', 'resort_name': 'Verbier'},
    'Zell am See': {'airport_code': 'airport-20', 'airport_name': 'Salzburg Airport', 'resort_code': 'resort-173', 'resort_name': 'Zell am See'},
    'Zermatt': {'airport_code': 'airport-1', 'airport_name': 'Geneva Airport', 'resort_code': 'resort-256', 'resort_name': 'Zermatt - Täsch/ Taesch'},
}

#: resorts with no usable code pair, with the exact reason --
#: these fall back to the generic booking form.
UNRESOLVED = {
    'Astún-Candanchú': "resort 'Astún-Candanchú' unmatched",
    'Formigal': "resort 'Formigal' unmatched",
    'Gudauri': "airport 'Tbilisi' unmatched; resort 'Gudauri' unmatched",
    'Kranjska Gora': "airport 'Ljubljana' unmatched",
    'Krvavec': "airport 'Ljubljana' unmatched; resort 'Krvavec' unmatched",
    'Obergurgl-Hochgurgl': "resort 'Obergurgl-Hochgurgl' unmatched",
    'Poiana Brasov': "airport 'Bucharest' unmatched; resort 'Poiana Brasov' unmatched",
    'Sella Ronda (Dolomiti)': "airport 'Verona' unmatched; resort 'Sella Ronda (Dolomiti)' unmatched",
    'Vallnord (Pal-Arinsal)': "resort 'Vallnord (Pal-Arinsal)' unmatched",
}
