"""
REAL Alps2Alps transfer quotes, frozen per resort.

GENERATED by scripts/build_transfer_quotes.py -- do not hand-edit.
Captured for 2 passengers, pickup 2027-01-09 10:00,
cheapest vehicle on each route, EUR, one-way.

WHY FROZEN: Alps2Alps allows ~14 API calls before a 429 whose
cooldown exceeds ten minutes (measured). A 12-result search would
need ~36 calls, so live per-search quoting is impossible -- this is
how real Alps2Alps numbers reach the user at all.

UNQUOTED_ROUTES records, per resort, exactly WHY no quote exists.
"""

TRANSFER_QUOTES: dict[str, dict] = {
    "Alpe d'Huez": {
        "price_eur": 346.5,
        "duration_minutes": 130.0,
        "vehicle": None,
        "vehicles_offered": 3,
    },
    'Avoriaz': {
        "price_eur": 302.5,
        "duration_minutes": 130.0,
        "vehicle": None,
        "vehicles_offered": 3,
    },
    'Bansko': {
        "price_eur": 222.0,
        "duration_minutes": 180.0,
        "vehicle": None,
        "vehicles_offered": 2,
    },
    'Bardonecchia': {
        "price_eur": 384.0,
        "duration_minutes": 155.0,
        "vehicle": None,
        "vehicles_offered": 3,
    },
    'Cervinia (Breuil-Cervinia)': {
        "price_eur": 546.0,
        "duration_minutes": 210.0,
        "vehicle": None,
        "vehicles_offered": 3,
    },
    'Chamonix': {
        "price_eur": 286.0,
        "duration_minutes": 110.0,
        "vehicle": None,
        "vehicles_offered": 3,
    },
    "Cortina d'Ampezzo": {
        "price_eur": 432.0,
        "duration_minutes": 200.0,
        "vehicle": None,
        "vehicles_offered": 3,
    },
    'Courchevel': {
        "price_eur": 385.0,
        "duration_minutes": 110.0,
        "vehicle": None,
        "vehicles_offered": 3,
    },
    'Grand Massif (Flaine)': {
        "price_eur": 297.0,
        "duration_minutes": 110.0,
        "vehicle": None,
        "vehicles_offered": 3,
    },
    'Grandvalira (Andorra)': {
        "price_eur": 582.0,
        "duration_minutes": 220.0,
        "vehicle": None,
        "vehicles_offered": 3,
    },
    'Ischgl': {
        "price_eur": 318.0,
        "duration_minutes": 110.0,
        "vehicle": None,
        "vehicles_offered": 3,
    },
    'Kitzbühel': {
        "price_eur": 306.0,
        "duration_minutes": 145.0,
        "vehicle": None,
        "vehicles_offered": 3,
    },
    'Les Arcs': {
        "price_eur": 385.0,
        "duration_minutes": 130.0,
        "vehicle": None,
        "vehicles_offered": 3,
    },
    'Les Deux Alpes': {
        "price_eur": 363.0,
        "duration_minutes": 130.0,
        "vehicle": None,
        "vehicles_offered": 3,
    },
    'Les Menuires': {
        "price_eur": 396.0,
        "duration_minutes": 120.0,
        "vehicle": None,
        "vehicles_offered": 3,
    },
    'Livigno': {
        "price_eur": 684.0,
        "duration_minutes": 340.0,
        "vehicle": None,
        "vehicles_offered": 3,
    },
    'Mayrhofen': {
        "price_eur": 270.0,
        "duration_minutes": 75.0,
        "vehicle": None,
        "vehicles_offered": 3,
    },
    'Méribel': {
        "price_eur": 363.0,
        "duration_minutes": 110.0,
        "vehicle": None,
        "vehicles_offered": 3,
    },
    'Pamporovo': {
        "price_eur": 252.0,
        "duration_minutes": 130.0,
        "vehicle": None,
        "vehicles_offered": 2,
    },
    'Passo Tonale': {
        "price_eur": 456.0,
        "duration_minutes": 210.0,
        "vehicle": None,
        "vehicles_offered": 3,
    },
    'Saalbach-Hinterglemm': {
        "price_eur": 360.0,
        "duration_minutes": 110.0,
        "vehicle": None,
        "vehicles_offered": 3,
    },
    'Serre Chevalier': {
        "price_eur": 534.0,
        "duration_minutes": 130.0,
        "vehicle": None,
        "vehicles_offered": 3,
    },
    'St. Anton am Arlberg': {
        "price_eur": 408.0,
        "duration_minutes": 120.0,
        "vehicle": None,
        "vehicles_offered": 3,
    },
    'Sölden': {
        "price_eur": 300.0,
        "duration_minutes": 90.0,
        "vehicle": None,
        "vehicles_offered": 3,
    },
    'Val Gardena (Selva)': {
        "price_eur": 594.0,
        "duration_minutes": 255.0,
        "vehicle": None,
        "vehicles_offered": 3,
    },
    'Val Thorens': {
        "price_eur": 423.5,
        "duration_minutes": 200.0,
        "vehicle": None,
        "vehicles_offered": 3,
    },
    "Val d'Isère / Tignes": {
        "price_eur": 429.0,
        "duration_minutes": 155.0,
        "vehicle": None,
        "vehicles_offered": 3,
    },
    'Verbier': {
        "price_eur": 516.0,
        "duration_minutes": 170.0,
        "vehicle": None,
        "vehicles_offered": 3,
    },
    'Zell am See': {
        "price_eur": 318.0,
        "duration_minutes": 110.0,
        "vehicle": None,
        "vehicles_offered": 3,
    },
    'Zermatt': {
        "price_eur": 618.0,
        "duration_minutes": 240.0,
        "vehicle": None,
        "vehicles_offered": 3,
    },
}

#: resort -> the precise reason Alps2Alps cannot quote it.
UNQUOTED_ROUTES: dict[str, str] = {
    'Astún-Candanchú': "Alps2Alps recognises no destination among ['Astún-Candanchú', 'Astún Candanchú']",
    'Formigal': "Alps2Alps recognises no destination among ['Formigal']",
    'Gudauri': "Alps2Alps recognises no airport among ['Tbilisi']",
    'Kranjska Gora': "Alps2Alps recognises no airport among ['Ljubljana']",
    'Krvavec': "Alps2Alps recognises no airport among ['Ljubljana']",
    'Obergurgl-Hochgurgl': "Alps2Alps recognises no destination among ['Obergurgl-Hochgurgl', 'Obergurgl Hochgurgl']",
    'Poiana Brasov': "Alps2Alps recognises no airport among ['Bucharest']",
    'Sella Ronda (Dolomiti)': "Alps2Alps recognises no airport among ['Verona']",
    'Vallnord (Pal-Arinsal)': "Alps2Alps recognises no destination among ['Vallnord (Pal-Arinsal)', 'Pal-Arinsal', 'Vallnord', '(Pal-Arinsal)', 'Vallnord (Pal Arinsal)']",
}
