"""
REAL airport-to-resort driving times, frozen from the Google Maps
Directions API.

GENERATED by scripts/build_transfer_drive_times.py -- do not hand-edit.
Keyed 'Resort Name|IATA' so multi-gateway resorts carry one row per
gateway. minutes = typical driving time, km = road distance.

Frozen because road geography is stable and 39 one-off requests cost
nothing, while per-search calls would be billable forever. Re-run the
generator when resorts or gateways change.
"""

DRIVE_TIMES: dict[str, dict] = {
    "Alpe d'Huez|GNB": {"minutes": 93, "km": 106.1},
    "Alpe d'Huez|LYS": {"minutes": 119, "km": 153.7},
    'Astún-Candanchú|BCN': {"minutes": 229, "km": 362.5},
    'Astún-Candanchú|ZAZ': {"minutes": 123, "km": 177.4},
    'Avoriaz|GVA': {"minutes": 99, "km": 102.5},
    'Bansko|SOF': {"minutes": 125, "km": 159.5},
    'Bardonecchia|TRN': {"minutes": 77, "km": 102.8},
    'Cervinia (Breuil-Cervinia)|MXP': {"minutes": 137, "km": 182.6},
    'Cervinia (Breuil-Cervinia)|TRN': {"minutes": 99, "km": 120.8},
    'Chamonix|GVA': {"minutes": 69, "km": 100.0},
    "Cortina d'Ampezzo|INN": {"minutes": 159, "km": 163.2},
    "Cortina d'Ampezzo|VCE": {"minutes": 115, "km": 147.5},
    'Courchevel|CMF': {"minutes": 85, "km": 103.0},
    'Courchevel|GVA': {"minutes": 128, "km": 134.7},
    'Formigal|BCN': {"minutes": 227, "km": 352.7},
    'Formigal|ZAZ': {"minutes": 121, "km": 167.6},
    'Grand Massif (Flaine)|GVA': {"minutes": 77, "km": 89.0},
    'Grandvalira (Andorra)|BCN': {"minutes": 167, "km": 208.8},
    'Grandvalira (Andorra)|TLS': {"minutes": 148, "km": 179.4},
    'Gudauri|TBS': {"minutes": 155, "km": 136.5},
    'Ischgl|INN': {"minutes": 81, "km": 99.8},
    'Ischgl|MUC': {"minutes": 195, "km": 236.6},
    'Kitzbühel|INN': {"minutes": 85, "km": 97.8},
    'Kitzbühel|MUC': {"minutes": 117, "km": 164.3},
    'Kitzbühel|SZG': {"minutes": 73, "km": 73.3},
    'Kranjska Gora|LJU': {"minutes": 50, "km": 63.7},
    'Kranjska Gora|VCE': {"minutes": 152, "km": 227.5},
    'Krvavec|LJU': {"minutes": 42, "km": 22.6},
    'Krvavec|VCE': {"minutes": 196, "km": 269.8},
    'Les Arcs|CMF': {"minutes": 110, "km": 127.9},
    'Les Arcs|GVA': {"minutes": 153, "km": 159.6},
    'Les Deux Alpes|GNB': {"minutes": 113, "km": 119.6},
    'Les Deux Alpes|LYS': {"minutes": 139, "km": 167.2},
    'Les Menuires|CMF': {"minutes": 96, "km": 113.8},
    'Les Menuires|GVA': {"minutes": 139, "km": 145.6},
    'Livigno|BGY': {"minutes": 202, "km": 178.1},
    'Livigno|INN': {"minutes": 164, "km": 179.4},
    'Mayrhofen|INN': {"minutes": 65, "km": 73.9},
    'Mayrhofen|MUC': {"minutes": 134, "km": 193.5},
    'Méribel|CMF': {"minutes": 77, "km": 122.8},
    'Méribel|GVA': {"minutes": 55, "km": 77.9},
    'Obergurgl-Hochgurgl|INN': {"minutes": 94, "km": 99.2},
    'Pamporovo|PDV': {"minutes": 89, "km": 78.0},
    'Pamporovo|SOF': {"minutes": 180, "km": 225.2},
    'Passo Tonale|BGY': {"minutes": 132, "km": 127.3},
    'Passo Tonale|BZO': {"minutes": 111, "km": 110.5},
    'Passo Tonale|VRN': {"minutes": 149, "km": 179.5},
    'Poiana Brasov|GHV': {"minutes": 31, "km": 21.3},
    'Poiana Brasov|OTP': {"minutes": 147, "km": 156.6},
    'Saalbach-Hinterglemm|MUC': {"minutes": 166, "km": 214.6},
    'Saalbach-Hinterglemm|SZG': {"minutes": 85, "km": 86.5},
    'Sella Ronda (Dolomiti)|INN': {"minutes": 173, "km": 174.8},
    'Sella Ronda (Dolomiti)|VCE': {"minutes": 135, "km": 154.3},
    'Sella Ronda (Dolomiti)|VRN': {"minutes": 154, "km": 193.4},
    'Serre Chevalier|GNB': {"minutes": 180, "km": 164.4},
    'Serre Chevalier|TRN': {"minutes": 142, "km": 136.4},
    'St. Anton am Arlberg|INN': {"minutes": 73, "km": 95.6},
    'Sölden|INN': {"minutes": 93, "km": 97.5},
    'Sölden|MUC': {"minutes": 212, "km": 256.5},
    'Val Gardena (Selva)|BZO': {"minutes": 57, "km": 46.9},
    'Val Gardena (Selva)|INN': {"minutes": 114, "km": 119.9},
    'Val Gardena (Selva)|VRN': {"minutes": 141, "km": 192.2},
    'Val Thorens|CMF': {"minutes": 108, "km": 123.4},
    'Val Thorens|GVA': {"minutes": 151, "km": 155.2},
    "Val d'Isère / Tignes|CMF": {"minutes": 130, "km": 145.9},
    "Val d'Isère / Tignes|GVA": {"minutes": 172, "km": 177.6},
    "Val d'Isère / Tignes|LYS": {"minutes": 174, "km": 223.0},
    'Vallnord (Pal-Arinsal)|BCN': {"minutes": 172, "km": 215.8},
    'Verbier|GVA': {"minutes": 113, "km": 160.4},
    'Zell am See|MUC': {"minutes": 157, "km": 204.7},
    'Zell am See|SZG': {"minutes": 76, "km": 76.5},
    'Zermatt|GVA': {"minutes": 160, "km": 229.5},
    'Zermatt|MXP': {"minutes": 162, "km": 167.3},
}

#: route -> why Google could not measure it.
UNMEASURED_ROUTES: dict[str, str] = {
}
