"""
Freeze REAL airport-to-resort driving distances and times from the
Google Maps Directions API -- one row per (resort, gateway airport).

WHY THIS EXISTS: Alps2Alps quotes real PRICES but only for the routes
they serve; a measured pass over all 39 resorts left 16 gaps (Spanish
Pyrenees, Georgia, some Italian gateways -- genuinely outside an Alps
transfer operator's network). Driving time is the other half of the
transfer story and Google can answer it for every route, so no resort
is left with an unsourced estimate.

Also replaces guesswork we had been carrying in the spreadsheet: the
transfer_time_text column mixes real figures with "~1h (est.)" values.
These are measured road distances and durations.

FROZEN, like the lift coordinates and the Alps2Alps quotes: road
geography is stable, and 39 one-off requests cost nothing against
Maps' free allowance while per-search calls would be billable forever.

Usage: PYTHONPATH=. python3 scripts/build_transfer_drive_times.py
"""
import os
import re
import time

import requests

from ski_optimizer.data.resort_repository import load_resorts

OUT = "ski_optimizer/data/transfer_drive_times.py"

#: Resorts whose bare name geocodes to the WRONG place. Caught by
#: cross-checking every measured road distance against the database's
#: own airport distance: "Les Arcs" matched the village in Provence,
#: giving 462km from Chambery instead of ~130km -- exactly the
#: plausible-looking wrong number this project forbids shipping.
_DESTINATION_OVERRIDES = {
    "Les Arcs": "Les Arcs 1800, Bourg-Saint-Maurice, France",
}
_IATA = re.compile(r"\(([A-Z]{3})\)")


def _api_key() -> str:
    key = os.environ.get("GOOGLE_MAPS_API_KEY")
    if not key and os.path.exists(".env"):
        for line in open(".env"):
            if line.startswith("GOOGLE_MAPS_API_KEY="):
                key = line.split("=", 1)[1].strip()
    if not key:
        raise SystemExit("GOOGLE_MAPS_API_KEY not set")
    return key


def airport_entries(field: str):
    """Every '<city> (IATA)' pair in a resort's airport field, so a
    multi-gateway resort gets a row per gateway."""
    for chunk in (field or "").split("/"):
        match = _IATA.search(chunk)
        if match:
            yield chunk.split("(")[0].strip(), match.group(1)


def main() -> None:
    key = _api_key()
    rows, gaps = {}, {}
    for resort in load_resorts():
        for city, iata in airport_entries(resort.nearest_airport):
            try:
                resp = requests.get(
                    "https://maps.googleapis.com/maps/api/directions/json",
                    params={"origin": f"{city} Airport ({iata})",
                            "destination": _DESTINATION_OVERRIDES.get(
                                resort.name, f"{resort.name}, {resort.country}"),
                            "mode": "driving", "key": key},
                    timeout=25)
                data = resp.json()
            except Exception as exc:  # noqa: BLE001
                gaps[f"{resort.name}|{iata}"] = f"request failed: {exc}"[:160]
                continue

            if data.get("status") != "OK" or not data.get("routes"):
                gaps[f"{resort.name}|{iata}"] = (
                    f"Google Directions returned {data.get('status')}"
                    f"{': ' + data['error_message'] if data.get('error_message') else ''} "
                    f"for {city} ({iata}) -> {resort.name}")[:200]
                print(f'  GAP  {resort.name[:24]:<26} {iata}: {data.get("status")}', flush=True)
                continue

            leg = data["routes"][0]["legs"][0]
            rows[f"{resort.name}|{iata}"] = {
                "minutes": round(leg["duration"]["value"] / 60),
                "km": round(leg["distance"]["value"] / 1000, 1),
            }
            print(f'  OK   {resort.name[:24]:<26} {iata}: '
                  f'{rows[f"{resort.name}|{iata}"]["km"]}km / '
                  f'{rows[f"{resort.name}|{iata}"]["minutes"]}min', flush=True)
            time.sleep(0.3)

    lines = ['"""',
             "REAL airport-to-resort driving times, frozen from the Google Maps",
             "Directions API.",
             "",
             "GENERATED by scripts/build_transfer_drive_times.py -- do not hand-edit.",
             "Keyed 'Resort Name|IATA' so multi-gateway resorts carry one row per",
             "gateway. minutes = typical driving time, km = road distance.",
             "",
             "Frozen because road geography is stable and 39 one-off requests cost",
             "nothing, while per-search calls would be billable forever. Re-run the",
             "generator when resorts or gateways change.",
             '"""',
             "",
             "DRIVE_TIMES: dict[str, dict] = {"]
    for k in sorted(rows):
        lines.append(f'    {k!r}: {{"minutes": {rows[k]["minutes"]}, "km": {rows[k]["km"]}}},')
    lines.append("}")
    lines.append("")
    lines.append("#: route -> why Google could not measure it.")
    lines.append("UNMEASURED_ROUTES: dict[str, str] = {")
    for k in sorted(gaps):
        lines.append(f"    {k!r}: {gaps[k]!r},")
    lines.append("}")
    open(OUT, "w").write("\n".join(lines) + "\n")
    print(f"\nwrote {len(rows)} routes, {len(gaps)} gaps -> {OUT}")


if __name__ == "__main__":
    main()
