"""
One-off builder: freeze Alps2Alps location codes for every resort.

WHY FROZEN: the booking deep link
(booking.alps2alps.com/booking/quick-checkout?from=<airport-code>&
to=<resort-code>&date=...&time=...&adults=...) is fully parameterized
-- verified live 2026-08-29: without a vehicle id it lands inside the
real funnel (step-3) with the actual route loaded. With the codes
frozen, EVERY search result gets a real prefilled transfer page with
ZERO API calls at search time -- the same fetch-once-ship-as-data
pattern as transfer_drive_times.py and ski_lift_locations.py, and the
only pattern that survives Alps2Alps' rate limits (~14 rapid calls to
/transfer-options then a 429 with a >10min cooldown, measured
2026-08-28).

Respects the documented 30 req/min on /locations/search: one request
every 2.5s. Reuses the adapter's own battle-tested name_variants
resolution (most "no match" results are spelling mismatches, not
missing coverage).

Run: .venv/bin/python scripts/build_alps2alps_locations.py
Output: ski_optimizer/data/alps2alps_locations.py
"""
import sys
import time
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent.parent))

from ski_optimizer.adapters.transfer_adapter import (  # noqa: E402
    _airport_city_name, name_variants, _fetch_json)
from ski_optimizer.data.resort_repository import load_resorts  # noqa: E402

PAUSE_S = 2.5


def resolve(query: str, location_type: str):
    """(code, matched_name) via name variants, politely paced."""
    for variant in name_variants(query):
        time.sleep(PAUSE_S)
        try:
            data = _fetch_json("/locations/search", {"q": variant})
        except Exception as exc:
            print(f"    ! {variant!r}: {exc}")
            continue
        match = next((i for i in (data or []) if i.get("type") == location_type), None)
        if match:
            return match["code"], match.get("name"), variant
    return None, None, None


def main():
    resorts = load_resorts()
    airport_cache: dict = {}
    resolved: dict = {}
    unresolved: dict = {}

    for r in resorts:
        airport_city = _airport_city_name(r.nearest_airport)
        if airport_city in airport_cache:
            a_code, a_name = airport_cache[airport_city]
        else:
            a_code, a_name, _ = resolve(airport_city, "airport")
            airport_cache[airport_city] = (a_code, a_name)
        rs_code, rs_name, _ = resolve(r.name, "resort")

        if a_code and rs_code:
            resolved[r.name] = {
                "airport_code": a_code, "airport_name": a_name,
                "resort_code": rs_code, "resort_name": rs_name,
            }
            print(f"OK  {r.name}: {a_code} ({a_name}) -> {rs_code} ({rs_name})")
        else:
            missing = []
            if not a_code:
                missing.append(f"airport {airport_city!r} unmatched")
            if not rs_code:
                missing.append(f"resort {r.name!r} unmatched")
            unresolved[r.name] = "; ".join(missing)
            print(f"--  {r.name}: {unresolved[r.name]}")

    out = Path(__file__).resolve().parent.parent / "ski_optimizer" / "data" / "alps2alps_locations.py"
    with open(out, "w") as f:
        f.write('"""\n')
        f.write("Alps2Alps location codes, frozen -- generated by\n")
        f.write("scripts/build_alps2alps_locations.py (see its docstring for why\n")
        f.write("frozen and how the deep link is built from these). Codes are the\n")
        f.write("provider's own stable place ids; regenerate if resorts change or\n")
        f.write('a link starts 404ing.\n"""\n\n')
        f.write("#: resort name -> codes for the booking deep link.\n")
        f.write("ALPS2ALPS_LOCATIONS = {\n")
        for name in sorted(resolved):
            f.write(f"    {name!r}: {resolved[name]!r},\n")
        f.write("}\n\n")
        f.write("#: resorts with no usable code pair, with the exact reason --\n")
        f.write("#: these fall back to the generic booking form.\n")
        f.write("UNRESOLVED = {\n")
        for name in sorted(unresolved):
            f.write(f"    {name!r}: {unresolved[name]!r},\n")
        f.write("}\n")
    print(f"\nwrote {out}: {len(resolved)} resolved, {len(unresolved)} unresolved")


if __name__ == "__main__":
    main()
