"""
ONE-TIME (re-runnable) generator: fetch every resort's ski-lift
coordinates from OpenStreetMap and freeze them into
ski_optimizer/data/ski_lift_locations.py.

WHY FROZEN AND NOT FETCHED AT RUNTIME: lift geography does not change
between searches, and the public Overpass API 504s from Cloud Run's IP
(measured in production 2026-08-28) -- so a runtime dependency on it
made the feature fail exactly where it needed to work. Shipping the
coordinates makes distance-to-lifts instant, free, offline and
unfailing; re-run this script when resorts are added or a season's
lift map changes.

Usage: PYTHONPATH=. python3 scripts/build_lift_locations.py
"""
import time

from ski_optimizer.adapters.lift_distance import fetch_lift_points
from ski_optimizer.data.resort_repository import load_resorts

# Only the nearest N points per resort are kept: the nearest-lift
# answer never depends on the 200th-closest lift, and this keeps the
# shipped file small and readable.
_KEEP_PER_RESORT = 60


def main() -> None:
    rows = {}
    for resort in load_resorts():
        if resort.latitude is None or resort.longitude is None:
            print(f"  {resort.name}: no coordinates, skipped")
            continue
        points = fetch_lift_points(resort.latitude, resort.longitude)
        if not points:
            print(f"  {resort.name}: NO LIFT DATA")
            continue
        # Closest to the resort centre first, then truncate.
        from ski_optimizer.adapters.lift_distance import haversine_km
        points.sort(key=lambda p: haversine_km(resort.latitude, resort.longitude, p[0], p[1]))
        rows[resort.name] = [(round(p[0], 5), round(p[1], 5)) for p in points[:_KEEP_PER_RESORT]]
        print(f"  {resort.name}: {len(rows[resort.name])} lift points")
        time.sleep(3)  # be a good citizen of a free public API

    out = ['"""',
           "Ski-lift coordinates per resort, frozen from OpenStreetMap.",
           "",
           "GENERATED by scripts/build_lift_locations.py -- do not hand-edit.",
           "Source: OpenStreetMap `aerialway` data (stations, gondolas,",
           "chairlifts, cable cars, funiculars) within 6km of each resort",
           "centre, nearest first, capped per resort.",
           "",
           "Frozen rather than queried live because lift geography is static",
           "and the public Overpass API 504s from Cloud Run's IP -- see",
           "adapters/lift_distance.py. (c) OpenStreetMap contributors, ODbL.",
           '"""',
           "",
           "SKI_LIFT_COORDS: dict[str, list[tuple[float, float]]] = {"]
    for name in sorted(rows):
        out.append(f'    {name!r}: [')
        for lat, lon in rows[name]:
            out.append(f"        ({lat}, {lon}),")
        out.append("    ],")
    out.append("}")
    with open("ski_optimizer/data/ski_lift_locations.py", "w") as fh:
        fh.write("\n".join(out) + "\n")
    print(f"\nwrote {len(rows)} resorts")


if __name__ == "__main__":
    main()
