"""
One-off builder: freeze Omio position ids (airport -> resort) per resort.

Same fetch-once-ship-as-data pattern as build_alps2alps_locations.py,
and for the same reason: a station does not move, so resolving it live
on every search spends a provider request to learn something we
already know. With the ids frozen, a live price is ONE call.

Run: .venv/bin/python scripts/build_omio_positions.py
Output: ski_optimizer/data/omio_positions.py
"""
import sys
import time
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent.parent))

from ski_optimizer.adapters.omio_mcp_adapter import resolve_positions  # noqa: E402
from ski_optimizer.adapters.transfer_adapter import _airport_city_name  # noqa: E402
from ski_optimizer.data.resort_repository import load_resorts  # noqa: E402

PAUSE_S = 1.5


def main():
    resolved, unresolved = {}, {}
    for resort in load_resorts():
        airport = _airport_city_name(resort.nearest_airport)
        # The AIRPORT is the origin: a ski transfer starts where the
        # flight lands, so "Geneva Airport" not "Geneva".
        from_term = f"{airport} Airport" if "airport" not in airport.lower() else airport
        time.sleep(PAUSE_S)
        ids = resolve_positions(from_term, resort.name)
        if ids:
            resolved[resort.name] = {**ids, "from_term": from_term}
            print(f"OK  {resort.name}: {from_term} {ids['from_id']} -> {ids['to_id']}")
        else:
            unresolved[resort.name] = f"Omio matched no route for {from_term!r} -> {resort.name!r}"
            print(f"--  {resort.name}: unmatched")

    out = Path(__file__).resolve().parent.parent / "ski_optimizer" / "data" / "omio_positions.py"
    with open(out, "w") as f:
        f.write('"""\n')
        f.write("Omio position ids, frozen -- generated by\n")
        f.write("scripts/build_omio_positions.py. Ids are the provider's own\n")
        f.write("stable station/place ids; regenerate if resorts change or a\n")
        f.write('lookup starts failing.\n"""\n\n')
        f.write("#: resort name -> {'from_id': airport, 'to_id': resort}\n")
        f.write("OMIO_POSITIONS = {\n")
        for name in sorted(resolved):
            f.write(f"    {name!r}: {resolved[name]!r},\n")
        f.write("}\n\n")
        f.write("#: resorts Omio could not route to, with the exact reason.\n")
        f.write("UNRESOLVED = {\n")
        for name in sorted(unresolved):
            f.write(f"    {name!r}: {unresolved[name]!r},\n")
        f.write("}\n")
    print(f"\nwrote {out}: {len(resolved)} resolved, {len(unresolved)} unresolved")


if __name__ == "__main__":
    main()
